name: testapp  # ✅ Project name (must be lowercase, no spaces)
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: "none"

# Versioning
version: 1.0.0+1

# ✅ Fix: Add SDK constraint
environment:
  sdk: '>=3.7.0 <4.0.0'

# ✅ Dependencies
dependencies:
  flutter:
    sdk: flutter

  # 🎨 UI & Animations
  lottie: ^3.3.1  # ✅ For Lottie animations
  rive: ^0.13.20  # Advanced vector animations
  animated_text_kit: ^4.2.2  # For animated text effects
  flutter_glow: ^0.3.0  # Glow effects
  confetti: ^0.8.0  # Animated confetti effects

  # 🔥 Firebase (Authentication, Database)
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

  # 🌐 API Calls
  http: ^1.3.0

  # 🧩 State Management
  provider: ^6.1.2  # ✅ Downgraded from 6.1.5 to 6.1.2

# ✅ Developer Tools
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ✅ Flutter Settings
flutter:
  uses-material-design: true

  # ✅ Only include animations folder (No images)
  assets:
    - assets/animations/  
    - assets/animations/customer_support.json  # ✅ Ensure this file exists
